In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("result/lab2_data/Car_train.xlsx")

In [3]:
df['label'].values

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [4]:
df[:5]

f1     f2     f3    f4     f5   f6  label
0   high   high  5more  more  small  low      0
1   high    low      2     4    med  med      0
2  vhigh    med      4     4  small  med      0
3    low  vhigh      4     4  small  med      0
4    med  vhigh      3     4  small  low      0

In [5]:
train_labels = df.loc[:,'label']
del df['label']
train_data = df.iloc[:]
x_train, y_train = train_data.values, train_labels.values

In [6]:
x_train, y_train

(array([['high', 'high', '5more', 'more', 'small', 'low'],
        ['high', 'low', 2, 4, 'med', 'med'],
        ['vhigh', 'med', 4, 4, 'small', 'med'],
        ...,
        ['low', 'low', 3, 'more', 'big', 'med'],
        ['high', 'vhigh', 4, 'more', 'small', 'high'],
        ['vhigh', 'med', 3, 4, 'big', 'low']], dtype=object),
 array([0, 0, 0, ..., 1, 0, 0], dtype=int64))

In [ ]:
ax = sns.distplot(y_train)

In [8]:
import sys
sys.path.append('D:\learning\AI\experiment')
from utils import to_digit

In [9]:
x_train = to_digit(x_train)

In [10]:
x_train

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1.],
       [1., 2., 2., 1., 0., 1.],
       ...,
       [2., 1., 3., 0., 2., 1.],
       [0., 3., 2., 0., 0., 2.],
       [1., 2., 3., 1., 2., 0.]])

In [11]:
from utils import validate
from dt_model.tree import *

In [12]:
model = DecisionTreeClassifier()
validate(model, x_train, y_train)

(0.03715170278637771, 0.9628482972136223, 0.9086465667500119)